# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GreyListEntry(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, site_id: str=None, site_base_url: str=None, greylist_name: str=None, greylist_description: str=None, greylist_logo: str=None, greylist_url: str=None, site_added_date: date=None, site_type: str=None, site_screenshot: str=None, site_information_link: str=None):  # noqa: E501
        """GreyListEntry - a model defined in Swagger

        :param site_id: The site_id of this GreyListEntry.  # noqa: E501
        :type site_id: str
        :param site_base_url: The site_base_url of this GreyListEntry.  # noqa: E501
        :type site_base_url: str
        :param greylist_name: The greylist_name of this GreyListEntry.  # noqa: E501
        :type greylist_name: str
        :param greylist_description: The greylist_description of this GreyListEntry.  # noqa: E501
        :type greylist_description: str
        :param greylist_logo: The greylist_logo of this GreyListEntry.  # noqa: E501
        :type greylist_logo: str
        :param greylist_url: The greylist_url of this GreyListEntry.  # noqa: E501
        :type greylist_url: str
        :param site_added_date: The site_added_date of this GreyListEntry.  # noqa: E501
        :type site_added_date: date
        :param site_type: The site_type of this GreyListEntry.  # noqa: E501
        :type site_type: str
        :param site_screenshot: The site_screenshot of this GreyListEntry.  # noqa: E501
        :type site_screenshot: str
        :param site_information_link: The site_information_link of this GreyListEntry.  # noqa: E501
        :type site_information_link: str
        """
        self.swagger_types = {
            'site_id': str,
            'site_base_url': str,
            'greylist_name': str,
            'greylist_description': str,
            'greylist_logo': str,
            'greylist_url': str,
            'site_added_date': date,
            'site_type': str,
            'site_screenshot': str,
            'site_information_link': str
        }

        self.attribute_map = {
            'site_id': 'site_id',
            'site_base_url': 'site_baseURL',
            'greylist_name': 'greylist-name',
            'greylist_description': 'greylist-description',
            'greylist_logo': 'greylist-logo',
            'greylist_url': 'greylist-url',
            'site_added_date': 'site-added-date',
            'site_type': 'site-type',
            'site_screenshot': 'site-screenshot',
            'site_information_link': 'site-information-link'
        }
        self._site_id = site_id
        self._site_base_url = site_base_url
        self._greylist_name = greylist_name
        self._greylist_description = greylist_description
        self._greylist_logo = greylist_logo
        self._greylist_url = greylist_url
        self._site_added_date = site_added_date
        self._site_type = site_type
        self._site_screenshot = site_screenshot
        self._site_information_link = site_information_link

    @classmethod
    def from_dict(cls, dikt) -> 'GreyListEntry':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Grey-List-Entry of this GreyListEntry.  # noqa: E501
        :rtype: GreyListEntry
        """
        return util.deserialize_model(dikt, cls)

    @property
    def site_id(self) -> str:
        """Gets the site_id of this GreyListEntry.

        ID as provided by the server  # noqa: E501

        :return: The site_id of this GreyListEntry.
        :rtype: str
        """
        return self._site_id

    @site_id.setter
    def site_id(self, site_id: str):
        """Sets the site_id of this GreyListEntry.

        ID as provided by the server  # noqa: E501

        :param site_id: The site_id of this GreyListEntry.
        :type site_id: str
        """

        self._site_id = site_id

    @property
    def site_base_url(self) -> str:
        """Gets the site_base_url of this GreyListEntry.


        :return: The site_base_url of this GreyListEntry.
        :rtype: str
        """
        return self._site_base_url

    @site_base_url.setter
    def site_base_url(self, site_base_url: str):
        """Sets the site_base_url of this GreyListEntry.


        :param site_base_url: The site_base_url of this GreyListEntry.
        :type site_base_url: str
        """

        self._site_base_url = site_base_url

    @property
    def greylist_name(self) -> str:
        """Gets the greylist_name of this GreyListEntry.


        :return: The greylist_name of this GreyListEntry.
        :rtype: str
        """
        return self._greylist_name

    @greylist_name.setter
    def greylist_name(self, greylist_name: str):
        """Sets the greylist_name of this GreyListEntry.


        :param greylist_name: The greylist_name of this GreyListEntry.
        :type greylist_name: str
        """

        self._greylist_name = greylist_name

    @property
    def greylist_description(self) -> str:
        """Gets the greylist_description of this GreyListEntry.


        :return: The greylist_description of this GreyListEntry.
        :rtype: str
        """
        return self._greylist_description

    @greylist_description.setter
    def greylist_description(self, greylist_description: str):
        """Sets the greylist_description of this GreyListEntry.


        :param greylist_description: The greylist_description of this GreyListEntry.
        :type greylist_description: str
        """

        self._greylist_description = greylist_description

    @property
    def greylist_logo(self) -> str:
        """Gets the greylist_logo of this GreyListEntry.


        :return: The greylist_logo of this GreyListEntry.
        :rtype: str
        """
        return self._greylist_logo

    @greylist_logo.setter
    def greylist_logo(self, greylist_logo: str):
        """Sets the greylist_logo of this GreyListEntry.


        :param greylist_logo: The greylist_logo of this GreyListEntry.
        :type greylist_logo: str
        """

        self._greylist_logo = greylist_logo

    @property
    def greylist_url(self) -> str:
        """Gets the greylist_url of this GreyListEntry.


        :return: The greylist_url of this GreyListEntry.
        :rtype: str
        """
        return self._greylist_url

    @greylist_url.setter
    def greylist_url(self, greylist_url: str):
        """Sets the greylist_url of this GreyListEntry.


        :param greylist_url: The greylist_url of this GreyListEntry.
        :type greylist_url: str
        """

        self._greylist_url = greylist_url

    @property
    def site_added_date(self) -> date:
        """Gets the site_added_date of this GreyListEntry.


        :return: The site_added_date of this GreyListEntry.
        :rtype: date
        """
        return self._site_added_date

    @site_added_date.setter
    def site_added_date(self, site_added_date: date):
        """Sets the site_added_date of this GreyListEntry.


        :param site_added_date: The site_added_date of this GreyListEntry.
        :type site_added_date: date
        """

        self._site_added_date = site_added_date

    @property
    def site_type(self) -> str:
        """Gets the site_type of this GreyListEntry.

        selection in which type the site is classified  # noqa: E501

        :return: The site_type of this GreyListEntry.
        :rtype: str
        """
        return self._site_type

    @site_type.setter
    def site_type(self, site_type: str):
        """Sets the site_type of this GreyListEntry.

        selection in which type the site is classified  # noqa: E501

        :param site_type: The site_type of this GreyListEntry.
        :type site_type: str
        """
        allowed_values = ["shop_dropshipping", "shop_not_located_in_the_eu"]  # noqa: E501
        if site_type not in allowed_values:
            raise ValueError(
                "Invalid value for `site_type` ({0}), must be one of {1}"
                .format(site_type, allowed_values)
            )

        self._site_type = site_type

    @property
    def site_screenshot(self) -> str:
        """Gets the site_screenshot of this GreyListEntry.


        :return: The site_screenshot of this GreyListEntry.
        :rtype: str
        """
        return self._site_screenshot

    @site_screenshot.setter
    def site_screenshot(self, site_screenshot: str):
        """Sets the site_screenshot of this GreyListEntry.


        :param site_screenshot: The site_screenshot of this GreyListEntry.
        :type site_screenshot: str
        """

        self._site_screenshot = site_screenshot

    @property
    def site_information_link(self) -> str:
        """Gets the site_information_link of this GreyListEntry.


        :return: The site_information_link of this GreyListEntry.
        :rtype: str
        """
        return self._site_information_link

    @site_information_link.setter
    def site_information_link(self, site_information_link: str):
        """Sets the site_information_link of this GreyListEntry.


        :param site_information_link: The site_information_link of this GreyListEntry.
        :type site_information_link: str
        """

        self._site_information_link = site_information_link
